### ISSUE TITLE
Java R13 Checklist

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-java#1149]
## Package Location
* JAVA
** https://oss.sonatype.org/#nexus-search;quick~com.microsoft.bot

## GitHub Updates
** Move Samples **
- [x] Remove from SDK
- [x] Move to Samples (https://github.com/microsoft/BotBuilder-Samples/tree/Java-R13)

**Create New Branch**
- [x] Java  

**Setup Branch Protection on New Branch**
- [x] Java 

**Bump Version on Main**
- [x] Java (4.14.0-SNAPSHOT)

**Update Readme.md in main to reflect new branch**
- [x] Java 

**Branch Samples**
- [x] Java

**Create DRAFT Release**
- [x] Java [4.13.0](https://github.com/microsoft/botbuilder-java/releases/tag/untagged-dbea1eaab3b242f24860)

**Consolidate release notes and change logs**
- [x] Java 

**Apply Release Notes to DRAFT Release**
- [x] Java 

**Publish GitHub Release**
- [ ] Java 

## Testing Status 
**Acceptance testing:** 

**Simple Dialog Flow**
- [ ] Java

**Simple State Management**
- [ ] Java

**Welcome Messages**
- [ ] Java

**Prompts and Prompt Validations**
- [ ] Java

**Standard Cards**
- [ ] Java

**Adaptive Cards**
- [ ] Java

**Card Actions**
- [ ] Java

**Regex Checking**
- [ ] Java

**QnA Maker**
- [ ] Java

**LUIS**
- [ ] Java

**Dispatch**
- [ ] Java

**Attachments**
- [ ] Java

**Proactive Messages**
- [ ] Java

**Middleware**
- [ ] Java

**Translations**
- [ ] Java

**Authentication**
- [ ] Java

**Waterfalls and Dialog Sets**
- [ ] Java

**State Storage**
- [ ] Java

**Transcript Logging**
- [ ] Java

**Facebook-specific Events**
- [ ] Java

**Application Insights**
- [ ] Java

**Teams**
- [ ] Java

**Enterprise Bot Template**
- [ ] Java
