### ISSUE TITLE
[Libraries] Java Checklist

### ISSUE THREAD

**Issue by Batta32** [microsoft/botbuilder-java#1166]
### End to end validation
**bot-ai-luis-v3**
- [X] Code migration
- [X] Unit test migration
- [X] Documentation
- [X] Behavior

**bot-ai-qna**
- [X] Code migration
- [X] Unit test migration
- [X] Documentation
- [X] Behavior

**bot-applicationinsights**
- [X] Code migration
- [X] Unit test migration
- [X] Documentation
- [X] Behavior

**bot-azure**
- [ ] Code migration
- [ ] Unit test migration
- [ ] Documentation
- [ ] Behavior

**bot-builder**
- [ ] Code migration
- [ ] Unit test migration
- [ ] Documentation
- [ ] Behavior

**bot-connector**
- [ ] Code migration
- [ ] Unit test migration
- [ ] Documentation
- [ ] Behavior

**bot-dialogs**
- [ ] Code migration
- [ ] Unit test migration
- [ ] Documentation
- [ ] Behavior

**bot-integration-core**
- [ ] Code migration
- [ ] Documentation
- [ ] Behavior

**bot-integration-spring**
- [ ] Code migration
- [ ] Documentation
- [ ] Behavior

**bot-schema**
- [ ] Code migration
- [ ] Unit test migration
- [ ] Documentation
- [ ] Behavior

**Additional context**
All the libraries are listed [here](https://github.com/microsoft/botbuilder-java/tree/main/libraries).
