### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-java#744]
- [ ] 01.console-echo
- [x] 02.echo-bot
- [x] 03.welcome-user
- [ ] 05.multi-turn-prompt
- [ ] 06.using-cards
- [ ] 07.using-adaptive-cards
- [x] 08.suggested-actions
- [ ] 11.qnamaker
- [ ] 13.core-bot
- [ ] 14.nlp-with-dispatch
- [ ] 15.handling-attachments
- [x] 16.proactive-messages
- [ ] 17.multilingual-bot
- [ ] 18.bot-authentication
- [ ] 19.custom-dialogs
- [ ] 21.corebot-app-insights
- [ ] 23.facebook-events
- [ ] 24.bot-authentication-msgraph
- [ ] 25.message-reaction
- [ ] 40.timex-resolution
- [ ] 42.scaleout
- [ ] 43.complex-dialog
- [ ] 44.prompt-users-for-input
- [x] 45.state-management
- [ ] 46.teams-auth
- [x] 47.inspection
- [ ] 49.qnamaker-all-features
- [x] 50.teams-messaging-extensions-search
- [x] 51.teams-messaging-extensions-action
- [x] 52.teams-messaging-extensions-search-auth-config
- [x] 53.teams-messaging-extensions-action-preview
- [x] 54.teams-task-module
- [x] 55.teams-link-unfurling
- [x] 56.teams-file-upload
- [x] 57.teams-conversation-bot
- [x] 58.teams-start-new-thread-in-channel
- [ ] 60.slack-adapter
- [ ] 61.facebook-adapter
- [ ] 62.webex-adapter
- [ ] 63.twilio-adapter
- [ ] 80.skills-simple-bot-to-bot
- [ ] 81.skills-skilldialog

**Comment by tracyboehrer** [comment]
Closing.  Created issue for each sample.
