### ISSUE TITLE
Resolve Recognizer issues

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-java#901]
- [ ]	https://github.com/microsoft/Recognizers-Text/issues/2413 – a regex behaviour difference in Java
- [ ]	https://github.com/microsoft/Recognizers-Text/issues/1786 – mitigation of regex issues in difference Java versions don’t work in some SDKs
- [ ]	Missing Java port of the Sequence type (e-mail, phone numbers, etc.)
- [ ]	Missing Java port of the Timex resolver lib.
- [ ]	https://github.com/microsoft/Recognizers-Text/issues/2254 – result index off by one
- [ ]	https://github.com/microsoft/Recognizers-Text/issues/2253 – unit test failures on mvn install
